language: ruby
rvm:
  - 1.9.3
  - 1.9.2
env:
  - "RAILS_ENV=test DB=mysql2 BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite"
  - "RAILS_ENV=test DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite"
  - "RAILS_ENV=test DB=sqlite BUNDLE_WITHOUT=rmagick:mysql:mysql2:postgres"
script: "bundle exec rake"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get --no-install-recommends install bzr cvs darcs git mercurial subversion"
before_script:
  - "RAILS_ENV=production bundle exec rake ci:travis:prepare"
branches:
  only:
    - feature/rails3
    - feature/rails3.2
notifications:
  email: false
