language: ruby
rvm:
  - 1.9.3
env:
  # mysql2
  - "TEST_SUITE=cucumber         RAILS_ENV=test DB=mysql2   BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite:development"
  - "TEST_SUITE=test:units       RAILS_ENV=test DB=mysql2   BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite:development"
  - "TEST_SUITE=test:functionals RAILS_ENV=test DB=mysql2   BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite:development"
  - "TEST_SUITE=test:integration RAILS_ENV=test DB=mysql2   BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite:development"
  - "TEST_SUITE=spec             RAILS_ENV=test DB=mysql2   BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite:development"
  # postgres
  - "TEST_SUITE=cucumber         RAILS_ENV=test DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite:development"
  - "TEST_SUITE=test:units       RAILS_ENV=test DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite:development"
  - "TEST_SUITE=test:functionals RAILS_ENV=test DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite:development"
  - "TEST_SUITE=test:integration RAILS_ENV=test DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite:development"
  - "TEST_SUITE=spec             RAILS_ENV=test DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite:development"
script: "bundle exec rake $TEST_SUITE"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get --no-install-recommends install git subversion"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "RAILS_ENV=production bundle exec rake ci:travis:prepare"
notifications:
  email: false
