#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2017 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See docs/COPYRIGHT.rdoc for more details.
#++

language: ruby

rvm:
  - 2.5.1

sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - frontend/node_modules

branches:
  only:
    - master
    - dev
    - /^(stable|release)\/.*$/

env:
  global:
    - CI=true
    - RAILS_ENV=test
    - GECKODRIVER_VERSION="0.20.0"

  matrix:
    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=1 BOGUS=1"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=1 BOGUS=2"
    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=1 BOGUS=3"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=1 BOGUS=4"
    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=1 BOGUS=5"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=1 BOGUS=6"


before_install:

  - "echo `firefox -v`"
  # Install geckodriver
  - echo "Installing geckodriver ${GECKODRIVER_VERSION}"
  - wget https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - echo `geckodriver --version`
  # Install Node LTS Boron (6.9.1)
  - "nvm install 6.9.1"
  # work around https://github.com/travis-ci/travis-ci/issues/8969
  - travis_retry gem update --system
  - gem install bundler

bundler_args: --binstubs --without development production docker

before_script:
  - sh script/ci_setup.sh $TEST_SUITE $DB

script:
  - sh script/ci_runner.sh

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      # CE
      - secure: "YkbFN1VXIIKYqDkdH3MTyVyzf0D7wCmAApvMMtWwVX6XM8NZ8PocFd26Cb3NEVoNG9e4xo4XMOcSMhz8FhZ4GgQhV0+075yhYKt8nq12S9XabbuJq/pfmTKyTYk+5RK35TX5rJFsE54R5pjn+FA42b0N7/BsyOsoTLKv34Ei68bG1sV8m0Q5+wVcoB30be9BsUckKLG8OPglLG8ht13Sf5WZSwgMFrW8tlrexgh+U56LpkZDoVwidI/tgyMuBTHTiAa97M/YVzf5vl6Bsq9Y8VO6JVwN3Q8FYQydmp9nlaAIN79OfXtdjnKX79gqicUM3PzOUYASAFVfwbu1qx7Ugg8QUj9E9Z0fRu1yHK2u4qxwtQbraF6zlSzJUikvv7d5/EoW8SohfuACrs86GBUCaiQRa5q643qtI0W/7/bThGX28GHfgFTo1g/zttDXFa7iZuWjz6AsIrCzJBxL8LozzQHI94Z3H2/L6FwOU6ZZmWFSJ4dkODEdD9EbGUaHUzA5JmTvSopy5qIA7M2jFmv9NLPE0SjP4U352XTbMJ8MFaSvuJ7cGHPMBlYPWayk+RuL0PQuIIEQaFoxsae0moiCqzBVMDZv98N/BtLYIn8KkvleQbkqTdtO5lgMab5e4xJYD5frLnHmC7nPXh7c5ogbU0ILlF9L5XUcZz412PhDGYs="
      # MP
      - secure: "uhO7jqGYIL4QPPWwIzAKGvSuXI0E7n8HD9aoiYUO2nL9t0iW8TjpQ34ht1JhMGBiG8D86vjXXSWB+o0jEBACEYJ6GQhCTo2yuGaXoS3igBVs8Y2XD5M+nOF2OReeJ9RXOn9KvosXGfSxE8KX/6YuvzLKFV6CZL2/RKC2Euqr0MKMeiaGVaUgZxgYbReJsgfqHugZgOIQY7yeMvGoZXgDqj6oDwMyl993XVxoPcGRQV0laOAKN2+ZDo8LmE3xuKfEvmGLtYh+5zrsOTp3YRU7K/BgQlYrvUcYORj4XyzO2UAej/qRS5LqqrK5ZFwuwpH3NJYpFQNS4b0fq5IaA4dKz+N3TzNWp1oOWckE05/LWBWZYl1t8Xto0NIc2mMeSAzhV4CcAOc7W+fCNyCGxsRNpfDD2Tst02aQ+fi5pC3ITS7IskrpA86T+WVckDDjjsROGAUaYUTtMMDzWGcnP0815zoGW4cIGnjwcmCn8w9AE3D1ERUxAagIwLeXDtv2XBxphS58Pfqg1pmfywEVdIUs9DUbJ4WRH/oHnESLB0DG5i2BvHMplNBiBdxpKH7V3cYHyHFgl+ExjwfwLKZw75EyyjwfD7bmJmEUE9YpiXulzP/JRnUiQ5oorQ6fzVva4TTZ4jugc1xImiwpOv60sBSdEI+LnnVMQurhfC3HQSYl/wE="

addons:
  # Setting latest here due to the switch from old selenium bindings
  # to Marionette. At the date of this writing, ESR is Firefox 52 and has
  # bad support for it. Thus we use latest (59.0 as of this writing)
  firefox: "59.0"
  postgresql: "9.6"
