#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2018 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++


###################################
#
# This file was generated by
# openproject-devkit.
#
# Do not modify this file directly!
#
###################################

language: ruby

rvm:
  - 2.5.1

sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - frontend/node_modules

branches:
  only:
    - master
    - dev
    - /^(stable|release)\/.*$/

env:
  global:
    - CI=true
    - RAILS_ENV=test

  matrix:
    - "TEST_SUITE=npm"


    - "TEST_SUITE=spec_legacy       DB=mysql     GROUP_SIZE=1 GROUP=1"
    - "TEST_SUITE=spec_legacy       DB=postgres  GROUP_SIZE=1 GROUP=1"

    - "TEST_SUITE=cucumber       DB=mysql     GROUP_SIZE=1 GROUP=1"
    - "TEST_SUITE=cucumber       DB=postgres  GROUP_SIZE=1 GROUP=1"

    - "TEST_SUITE=specs       DB=mysql     GROUP_SIZE=4 GROUP=1"
    - "TEST_SUITE=specs       DB=postgres  GROUP_SIZE=4 GROUP=1"
    - "TEST_SUITE=specs       DB=mysql     GROUP_SIZE=4 GROUP=2"
    - "TEST_SUITE=specs       DB=postgres  GROUP_SIZE=4 GROUP=2"
    - "TEST_SUITE=specs       DB=mysql     GROUP_SIZE=4 GROUP=3"
    - "TEST_SUITE=specs       DB=postgres  GROUP_SIZE=4 GROUP=3"
    - "TEST_SUITE=specs       DB=mysql     GROUP_SIZE=4 GROUP=4"
    - "TEST_SUITE=specs       DB=postgres  GROUP_SIZE=4 GROUP=4"

    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=1"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=1"
    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=2"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=2"
    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=3"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=3"
    - "TEST_SUITE=features       DB=mysql     GROUP_SIZE=4 GROUP=4"
    - "TEST_SUITE=features       DB=postgres  GROUP_SIZE=4 GROUP=4"


before_install:

  # Install Node LTS Boron (6.9.1)
  - "nvm install 6.9.1"
  # work around https://github.com/travis-ci/travis-ci/issues/8969
  - travis_retry gem update --system
  - gem install bundler


bundler_args: --binstubs --without development production docker

before_script:
  - sh script/ci_setup.sh $TEST_SUITE $DB

script:
  - sh script/ci_runner.sh


addons:
  chrome: stable
  postgresql: "9.6"
