#-- copyright
# OpenProject is a project management system.
# Copyright (C) 2012-2018 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2018 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.rdoc for more details.
#++


###################################
#
# This file was generated by
# openproject-devkit.
#
# Do not modify this file directly!
#
###################################

language: ruby

rvm:
  - 2.5.1

sudo: required
dist: trusty

cache:
  bundler: true
  directories:
    - frontend/node_modules
    - public/assets
    - app/assets/javascripts/bundles
    - app/assets/javascripts/locales

branches:
  only:
    - master
    - dev
    - /^(stable|release)\/.*$/

env:
  global:
    - CI=true
    - RAILS_ENV=test

before_install:
  # work around https://github.com/travis-ci/travis-ci/issues/8969
  - travis_retry gem update --system
  # Don't install 1.16.3
  - gem install bundler -v 1.16.2

bundler_args: --binstubs --without development production docker

stages:
  - prepare cache
  - test

jobs:
  include:
    - stage: prepare cache
      name: 'Prepare cache'
      script:
        - bash script/ci_cache_prepare.sh
    - stage: test
      name: 'npm'
      script:
        - bash script/ci_setup.sh npm
        - bash script/ci_runner.sh npm
    - name: 'spec_legacy (1/1) - mysql'
      script:
      - bash script/ci_setup.sh spec_legacy mysql
      - bash script/ci_runner.sh spec_legacy 1 1
    - name: 'spec_legacy (1/1) - postgresql'
      script:
      - bash script/ci_setup.sh spec_legacy postgres
      - bash script/ci_runner.sh spec_legacy 1 1
    - name: 'cucumber (1/1) - mysql'
      script:
      - bash script/ci_setup.sh cucumber mysql
      - bash script/ci_runner.sh cucumber 1 1
    - name: 'cucumber (1/1) - postgresql'
      script:
      - bash script/ci_setup.sh cucumber postgres
      - bash script/ci_runner.sh cucumber 1 1
    - name: 'unit specs (1/4) - mysql'
      script:
      - bash script/ci_setup.sh specs mysql
      - bash script/ci_runner.sh specs 4 1
    - name: 'unit specs (1/4) - postgresql'
      script:
      - bash script/ci_setup.sh specs postgres
      - bash script/ci_runner.sh specs 4 1
    - name: 'unit specs (2/4) - mysql'
      script:
      - bash script/ci_setup.sh specs mysql
      - bash script/ci_runner.sh specs 4 2
    - name: 'unit specs (2/4) - postgresql'
      script:
      - bash script/ci_setup.sh spec postgres
      - bash script/ci_runner.sh specs 4 2
    - name: 'unit specs (3/4) - mysql'
      script:
      - bash script/ci_setup.sh specs mysql
      - bash script/ci_runner.sh specs 4 3
    - name: 'unit specs (3/4) - postgresql'
      script:
      - bash script/ci_setup.sh specs postgres
      - bash script/ci_runner.sh specs 4 3
    - name: 'unit specs (4/4) - mysql'
      script:
      - bash script/ci_setup.sh specs mysql
      - bash script/ci_runner.sh specs 4 4
    - name: 'unit specs (4/4) - postgresql'
      script:
      - bash script/ci_setup.sh specs postgres
      - bash script/ci_runner.sh specs 4 4
    - name: 'feature specs (1/4) - mysql'
      script:
      - bash script/ci_setup.sh features mysql
      - bash script/ci_runner.sh features 4 1
    - name: 'feature specs (1/4) - postgresql'
      script:
      - bash script/ci_setup.sh features postgres
      - bash script/ci_runner.sh features 4 1
    - name: 'feature specs (2/4) - mysql'
      script:
      - bash script/ci_setup.sh features mysql
      - bash script/ci_runner.sh features 4 2
    - name: 'feature specs (2/4) - postgresql'
      script:
      - bash script/ci_setup.sh features postgres
      - bash script/ci_runner.sh features 4 2
    - name: 'feature specs (3/4) - mysql'
      script:
      - bash script/ci_setup.sh features mysql
      - bash script/ci_runner.sh features 4 3
    - name: 'feature specs (3/4) - postgresql'
      script:
      - bash script/ci_setup.sh features postgres
      - bash script/ci_runner.sh features 4 3
    - name: 'feature specs (4/4) - mysql'
      script:
      - bash script/ci_setup.sh features mysql
      - bash script/ci_runner.sh features 4 4
    - name: 'feature specs (4/4) - postgresql'
      script:
      - bash script/ci_setup.sh features postgres
      - bash script/ci_runner.sh features 4 4


addons:
  chrome: stable
  postgresql: "9.6"
