db:
  image: postgres:9.6.3
  environment:
    POSTGRES_USER: app
    POSTGRES_PASSWORD: p4ssw0rd
    POSTGRES_DB: app
  volumes:
    - /var/lib/postgresql/data
  expose:
    - '5432'

web:
  build: .
  links:
    - db
  environment:
    - "RAILS_CACHE_STORE=file_store"
    - "DATABASE_URL=postgresql://app:p4ssw0rd@db:5432/app?encoding=utf8&pool=5&timeout=5000&reconnect=true"
    - "SECRET_KEY_BASE=d4e74f017910ac56c6ebad01165b7e1b37f4c9c02e9716836f8670cdc8d65a231e64e4f6416b19c8"
    - "RAILS_ENV=production"
    - "HEROKU=true"
  env_file: ./.env.pullpreview
  ports:
    - "80:8080"
  command: "./docker/web"
  volumes:
    - "/var/openproject/assets"

worker:
  build: .
  links:
    - db
  environment:
    - "RAILS_CACHE_STORE=file_store"
    - "DATABASE_URL=postgresql://app:p4ssw0rd@db:5432/app?encoding=utf8&pool=5&timeout=5000&reconnect=true"
    - "SECRET_KEY_BASE=d4e74f017910ac56c6ebad01165b7e1b37f4c9c02e9716836f8670cdc8d65a231e64e4f6416b19c8"
    - "RAILS_ENV=production"
    - "HEROKU=true"
  env_file: ./.env.pullpreview
  command: "./docker/worker --seed --set attachment_max_size=262144"
  volumes_from:
    - web
