# Schema: NotificationSettingModel
---
type: array
description: The settings for the notifications to be received by the user
items:
  type: object
  required:
    - watched
    - involved
    - mentioned
    - workPackageCreated
    - workPackageCommented
    - workPackageProcessed
    - workPackagePrioritized
    - workPackageScheduled
    - newsAdded
    - newsCommented
    - documentAdded
    - forumMessages
    - wikiPageAdded
    - wikiPageUpdated
    - membershipAdded
    - membershipUpdated
    - _links
  properties:
    documentAdded:
      type: boolean
    forumMessages:
      type: boolean
    involved:
      type: boolean
    membershipAdded:
      type: boolean
    membershipUpdated:
      type: boolean
    mentioned:
      type: boolean
    newsAdded:
      type: boolean
    newsCommented:
      type: boolean
    overdue:
      type: string
      description: |-
        Sets an overdue notification for work packages. It is null when no notification is set,
        otherwise it holds an ISO8601 formatted duration string with the possible values listed below.
        The possible values are: none, every day, every 3 days, every week.
      enum:
        - ""
        - PT0S
        - P3D
        - P1W
    startDate:
      type: string
      description: |-
        Sets a startDate notification for work packages. It is null when no notification is set,
        otherwise it holds an ISO8601 formatted duration string with the possible values listed below.
        The possible values are: none, same day, 1 day before, 3 days before, 1 week before.
      enum:
        - ""
        - PT0S
        - P1D
        - P3D
        - P1W
    dueDate:
      type: string
      description: |-
        Sets a dueDate notification for work packages. It is null when no notification is set,
        otherwise it holds an ISO8601 formatted duration string with the possible values listed below.
        The possible values are: none, same day, 1 day before, 3 days before, 1 week before.
      enum:
        - ""
        - PT0S
        - P1D
        - P3D
        - P1W
    watched:
      type: boolean
    workPackageCreated:
      type: boolean
    workPackageCommented:
      type: boolean
    workPackageProcessed:
      type: boolean
    workPackagePrioritized:
      type: boolean
    workPackageScheduled:
      type: boolean
    wikiPageAdded:
      type: boolean
    wikiPageUpdated:
      type: boolean
    _links:
      type: object
      required:
        - project
      properties:
        project:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              format: uri
