#-- copyright
# OpenProject is a project management system.
#
# Copyright (C) 2012-2013 the OpenProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# See doc/COPYRIGHT.rdoc for more details.
#++

mode: none
theme: advanced # openproject
skin: o2k7      # default
skin_variant: silver
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
plugins:
  - visualblocks
  - autolink
  - lists
  - style
  - table
  - advlink
  - template
  - inlinepopups
  - contextmenu
  - paste
  - noneditable
  - nonbreaking
  - xhtmlxtras
disabled_plugins: #not used by tinyMCE, its just here for documentation
  - openproject
  - advimage
  - iespell
  - spellchecker
  - visualchars
  - advhr
  - searchreplace
  - insertdatetime
  - media
theme_advanced_buttons1:
  - template
  - "|"
  - undo
  - redo
  - "|"
  - cut
  - copy
  - paste
  - pastetext
  - pasteword
  - "|"
  - cleanup
  - removeformat
  - "|"
  - visualaid
  - visualblocks
  - code
  - "|"
  - hr
  - image
  - nonbreaking
  - tablecontrols
theme_advanced_buttons2:
  - formatselect
  - "|"
  - bold
  - italic
  - underline
  - strikethrough
  - "|"
  - justifyleft
  - justifycenter
  - justifyright
  - justifyfull
  - "|"
  - bullist
  - numlist
  - "|"
  - outdent
  - indent
  - "|"
  - blockquote
  - "|"
  - forecolor
  - backcolor
  - "|"
  - link
  - unlink
  - "|"
  - sub
  - sup
  - acronym
theme_advanced_buttons3: []
theme_advanced_resizing: true
add_form_submit_trigger: true

template_cdate_classes: "cdate creationdate"
template_mdate_classes: "mdate modifieddate"
template_selected_content_classes: "selcontent"
template_cdate_format: "%m/%d/%Y : %H:%M:%S"
template_mdate_format: "%m/%d/%Y : %H:%M:%S"
template_templates:
  -
    title: "Status Report"
    src: "/assets/tiny_mce_assets/templates/status_report.html"
    description: "Adds a default project status report."
  -
    title: "Contact Information Page"
    src: "/assets/tiny_mce_assets/templates/contact_page.html"
    description: "Adds default contact information page."
