name: pullpreview

on:
  schedule:
    # this is used to make sure no dangling resources are left
    - cron: "30 2 * * *"
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  deploy:
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to delete deployments
      pull-requests: write # to remove labels
      statuses: write # to create commit status

    if: github.repository == 'opf/openproject' && ( github.event_name == 'schedule' || github.event_name == 'push' || github.event.label.name == 'pullpreview' || contains(github.event.pull_request.labels.*.name, 'pullpreview') )
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Generate .env.pullpreview file
      run: |
        echo "OP_ADMIN_USER_SEEDER_FORCE_PASSWORD_CHANGE=off" >> .env.pullpreview
        echo "OPENPROJECT_SHOW__SETTING__MISMATCH__WARNING=false" >> .env.pullpreview
        echo "OPENPROJECT_FEATURE__STORAGES__MODULE__ACTIVE=true" >> .env.pullpreview
    - name: Boot as BIM edition
      if: contains(github.ref, 'bim/') || contains(github.head_ref, 'bim/')
      run: |
        echo "OPENPROJECT_EDITION=bim" >> .env.pullpreview
    - name: Prepare docker-compose files
      run: |
        cp ./docker/pullpreview/docker-compose.yml ./docker-compose.pullpreview.yml
        cp ./docker/prod/Dockerfile ./Dockerfile
        cp ./docker/pullpreview-storybook/Dockerfile ./Dockerfile-storybook
    - uses: pullpreview/action@v5
      with:
        admins: crohr,HDinger,machisuji,oliverguenther,ulferts,wielinde,b12f,cbliard
        always_on: dev
        compose_files: docker-compose.pullpreview.yml
        instance_type: large_2_0
        ports: 80,443,8080
        default_port: 443
      env:
        AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        AWS_REGION: eu-central-1
